import {
  Activity,
  ArrowDownRight,
  ArrowUpRight,
  Bell,
  CalendarDays,
  CarFront,
  ChevronDown,
  CircleDollarSign,
  LayoutDashboard,
  Menu,
  MoreHorizontal,
  Plus,
  Settings2,
  ShieldCheck,
  WalletCards,
  X,
  Receipt,
  BarChart3,
  Database,
  CircleHelp,
  Landmark,
  IdCardLanyard,
  UsersRound,
  ChartLine,
  CircleQuestionMark,
  DollarSign,
  Truck,
  Wrench,
  Camera,
  Lock,
  Box,
  LibraryBig,
  LoaderPinwheel,
  ArchiveRestore,
  Siren,
  Handshake,
  FileText,
  Search,
} from "lucide-react";
import { NavItem, Permissoes } from "./types";



export const navGroups: { label: string; items: NavItem[] }[] = [
  {
    label: "Visão geral",
    items: [
      { href: "/dashboard", label: "Dashboard", resource: "dashboard", icon: LayoutDashboard },
    ],
  },
  {
    label: "Financeiro",
    items: [
      { href: "/contas-pagar", label: "Contas a pagar", resource: "contas_pagar", icon: Receipt },
      { href: "/contas-receber", label: "Contas a receber", resource: "contas_receber", icon: Receipt },
      { href: "/fluxo", label: "Fluxo de caixa", resource: "fluxo", icon: Landmark },
      { href: "/relatorios", label: "Relatórios", resource: "relatorios", icon: BarChart3 },
      { href: "/prejuizos", label: "Prejuízos", resource: "prejuizos", icon: ArrowDownRight },
      { href: "/funcionarios", label: "Funcionarios", resource: "funcionarios", icon: IdCardLanyard },
    ],
  },
  {
    label: "Faturamento",
    items: [
      { href: "/clientes", label: "Clientes", resource: "contas_pagar", icon: UsersRound },
      { href: "/proposta", label: "Proposta", resource: "contas_receber", icon: Receipt },
      { href: "/medicoes", label: "Medições", resource: "fluxo", icon: ChartLine },
      { href: "/ajuda-motoristas", label: "Ajuda Motoristas", resource: "relatorios", icon: CircleQuestionMark },
      { href: "/fatura-locacao", label: "Fatura Locação", resource: "prejuizos", icon: DollarSign },
    ],
  },
  {
    label: "Frota e Manutenção",
    items: [
      { href: "/frota", label: "Frota ", resource: "estoque", icon: Truck },
      { href: "/manutencao", label: "Manutenção", resource: "compras", icon: Wrench },
      { href: "/venda-avaria", label: "Venda/Avaria  ", resource: "compras", icon: CircleDollarSign },
      { href: "/acomp-revisao", label: "Acomp. Revisão", resource: "compras", icon: Wrench },
      { href: "/mobilizacao", label: "Mobilização", resource: "compras", icon: Camera },
      { href: "/seguro", label: "Seguro", resource: "compras", icon: Lock },
    ],
  },
  {
    label: "Estoque e Compras",
    items: [
      { href: "/estoque", label: "Estoque", resource: "checklist", icon: Box },
      { href: "/nf-e", label: "Nf-e", resource: "auditoria", icon: LibraryBig },
      { href: "/pneus", label: "Pneus", resource: "sistema", icon: LoaderPinwheel },
      { href: "/saida-de-material", label: "Saida de Material", resource: "ajuda", icon: ArchiveRestore },
    ],
  },
  {
    label: "Sistema",
    items: [
      { href: "/pendencias", label: "Pendencias", resource: "checklist", icon: Siren },
      { href: "/tratativas", label: "Tratativas", resource: "auditoria", icon: Handshake },
      { href: "/configuracoes", label: "Configurações", resource: "sistema", icon: Settings2 },
      { href: "/ajuda", label: "Ajuda", resource: "ajuda", icon: CircleHelp },
    ],
  },
  {
    label:"Configuracoes",
    items:[
      { href: "/usuarios", label: "Usuarios", resource: "configuracoes", icon: UsersRound },
    ]
  }
];


export const permissoesPadrao: Permissoes = {
  dash: false,
  whatsapp: false,
  adm: false,
  custo: true,
  preco: true,
  desc: true,
  "estq-edit": false,
  "venda-eq": false,
  "pneu-edit": false,
  rel: false,
  "rel-fin": false,
  "rel-os": true,
  "rel-frota": false,
  "rel-resultado": false,
  "rel-estq": true,
  "rel-cpagar": false,
  "rel-creceber": false,
  "rel-fin-imp": false,
  "rel-os-imp": true,
  "rel-frota-imp": false,
  "rel-resultado-imp": false,
  "rel-estq-imp": true,
  "rel-cpagar-imp": false,
  "rel-creceber-imp": false,
  "contas-dia": false,
  aniversarios: false,
  "confirma-ajuda": true,
  motivacao: true,
  "kpi-fin": false,
  "contas-banco": false,
  "backup-manual": false,
  exportar: false,
  "ajuda-custo": true,
  "ver-auditoria": false,
  "ver-resultado-placa": false,
  "gerenciar-usuarios": false,
  "enviar-email": false,
  seguro: false,
  "doc-veiculo": true,
  frota: true,
  "frota-criar": false,
  "frota-editar": false,
  "frota-excluir": false,
  manut: true,
  "manut-criar": true,
  "manut-editar": true,
  "manut-excluir": false,
  cts: false,
  "cts-criar": false,
  "cts-editar": false,
  "cts-excluir": false,
  meds: false,
  "meds-criar": false,
  "meds-editar": false,
  "meds-excluir": false,
  vend: true,
  "vend-criar": true,
  "vend-editar": true,
  "vend-excluir": false,
  estq: true,
  "estq-criar": true,
  "estq-editar": false,
  "estq-excluir": false,
  desp: false,
  "desp-criar": false,
  "desp-editar": false,
  "desp-excluir": false,
  fin: false,
  "fin-criar": false,
  "fin-editar": false,
  "fin-excluir": false,
  pneus: true,
  "pneus-criar": false,
  "pneus-editar": false,
  "pneus-excluir": false,
  resultado: false,
  "resultado-criar": false,
  "resultado-editar": false,
  "resultado-excluir": false,
  clientes: false,
  "clientes-criar": false,
  "clientes-editar": false,
  "clientes-excluir": false,
  mob: true,
  "mob-criar": false,
  "mob-editar": false,
  "mob-excluir": false,
  func: false,
  "func-criar": false,
  "func-editar": false,
  "func-excluir": false,
  prej: false,
  "prej-criar": false,
  "prej-editar": false,
  "prej-excluir": false,
  sm: true,
  "sm-criar": true,
  "sm-editar": true,
  "sm-excluir": false,
  sist: false,
  "sist-criar": false,
  "sist-editar": false,
  "sist-excluir": false,
  cpagar: false,
  "cpagar-criar": false,
  "cpagar-editar": false,
  "cpagar-excluir": false,
  creceber: false,
  "creceber-criar": false,
  "creceber-editar": false,
  "creceber-excluir": false,
  prop: true,
  "prop-criar": true,
  "prop-editar": true,
  "prop-excluir": false,
  tratativas: false,
  "tratativas-criar": false,
  "tratativas-editar": false,
  "tratativas-excluir": false,
  "fatloc-ver": false,
  "fatloc-criar": false,
  "fatloc-excluir": false,
  "fatloc-enviar": false,
};

export const nomesPermissoes: Record<string, string> = {
  dash: "Dashboard",
  whatsapp: "WhatsApp",
  adm: "Administração",
  custo: "Visualizar custo",
  preco: "Visualizar preço",
  desc: "Visualizar descrição",
  "estq-edit": "Editar estoque",
  "venda-eq": "Vender equipamento",
  "pneu-edit": "Editar pneus",
  rel: "Relatórios",
  "rel-fin": "Relatório financeiro",
  "rel-os": "Relatório de ordens de serviço",
  "rel-frota": "Relatório de frota",
  "rel-resultado": "Relatório de resultado",
  "rel-estq": "Relatório de estoque",
  "rel-cpagar": "Relatório de contas a pagar",
  "rel-creceber": "Relatório de contas a receber",
  "rel-fin-imp": "Imprimir relatório financeiro",
  "rel-os-imp": "Imprimir relatório de OS",
  "rel-frota-imp": "Imprimir relatório de frota",
  "rel-resultado-imp": "Imprimir relatório de resultado",
  "rel-estq-imp": "Imprimir relatório de estoque",
  "rel-cpagar-imp": "Imprimir relatório de contas a pagar",
  "rel-creceber-imp": "Imprimir relatório de contas a receber",
  "contas-dia": "Contas do dia",
  aniversarios: "Aniversários",
  "confirma-ajuda": "Confirmar ajuda",
  motivacao: "Motivação",
  "kpi-fin": "KPIs financeiros",
  "contas-banco": "Contas bancárias",
  "backup-manual": "Backup manual",
  exportar: "Exportar dados",
  "ajuda-custo": "Ajuda de custo",
  "ver-auditoria": "Visualizar auditoria",
  "ver-resultado-placa": "Resultado por placa",
  "gerenciar-usuarios": "Gerenciar usuários",
  "enviar-email": "Enviar e-mail",
  seguro: "Seguros",
  "doc-veiculo": "Documentos do veículo",
  frota: "Frota",
  "frota-criar": "Criar veículo",
  "frota-editar": "Editar veículo",
  "frota-excluir": "Excluir veículo",
  manut: "Manutenção",
  "manut-criar": "Criar manutenção",
  "manut-editar": "Editar manutenção",
  "manut-excluir": "Excluir manutenção",
  cts: "Contratos",
  "cts-criar": "Criar contrato",
  "cts-editar": "Editar contrato",
  "cts-excluir": "Excluir contrato",
  meds: "Medições",
  "meds-criar": "Criar medição",
  "meds-editar": "Editar medição",
  "meds-excluir": "Excluir medição",
  vend: "Vendas",
  "vend-criar": "Criar venda",
  "vend-editar": "Editar venda",
  "vend-excluir": "Excluir venda",
  estq: "Estoque",
  "estq-criar": "Criar item no estoque",
  "estq-editar": "Editar item do estoque",
  "estq-excluir": "Excluir item do estoque",
  desp: "Despesas",
  "desp-criar": "Criar despesa",
  "desp-editar": "Editar despesa",
  "desp-excluir": "Excluir despesa",
  fin: "Financeiro",
  "fin-criar": "Criar lançamento financeiro",
  "fin-editar": "Editar lançamento financeiro",
  "fin-excluir": "Excluir lançamento financeiro",
  pneus: "Pneus",
  "pneus-criar": "Criar pneu",
  "pneus-editar": "Editar pneu",
  "pneus-excluir": "Excluir pneu",
  resultado: "Resultado",
  "resultado-criar": "Criar resultado",
  "resultado-editar": "Editar resultado",
  "resultado-excluir": "Excluir resultado",
  clientes: "Clientes",
  "clientes-criar": "Criar cliente",
  "clientes-editar": "Editar cliente",
  "clientes-excluir": "Excluir cliente",
  mob: "Mobilização",
  "mob-criar": "Criar mobilização",
  "mob-editar": "Editar mobilização",
  "mob-excluir": "Excluir mobilização",
  func: "Funcionários",
  "func-criar": "Criar funcionário",
  "func-editar": "Editar funcionário",
  "func-excluir": "Excluir funcionário",
  prej: "Prejuízos",
  "prej-criar": "Criar prejuízo",
  "prej-editar": "Editar prejuízo",
  "prej-excluir": "Excluir prejuízo",
  sm: "Saída de material",
  "sm-criar": "Criar saída de material",
  "sm-editar": "Editar saída de material",
  "sm-excluir": "Excluir saída de material",
  sist: "Sistema",
  "sist-criar": "Criar configuração",
  "sist-editar": "Editar configuração",
  "sist-excluir": "Excluir configuração",
  cpagar: "Contas a pagar",
  "cpagar-criar": "Criar conta a pagar",
  "cpagar-editar": "Editar conta a pagar",
  "cpagar-excluir": "Excluir conta a pagar",
  creceber: "Contas a receber",
  "creceber-criar": "Criar conta a receber",
  "creceber-editar": "Editar conta a receber",
  "creceber-excluir": "Excluir conta a receber",
  prop: "Propostas",
  "prop-criar": "Criar proposta",
  "prop-editar": "Editar proposta",
  "prop-excluir": "Excluir proposta",
  tratativas: "Tratativas",
  "tratativas-criar": "Criar tratativa",
  "tratativas-editar": "Editar tratativa",
  "tratativas-excluir": "Excluir tratativa",
  "fatloc-ver": "Visualizar fatura de locação",
  "fatloc-criar": "Criar fatura de locação",
  "fatloc-excluir": "Excluir fatura de locação",
  "fatloc-enviar": "Enviar fatura de locação",
};